兼容性优化
sy-records/aliyun-oss-wordpress pull request #6
Opened 2021-11-05 07:55 UTC by 2551654928

2021-12-09 12:05 UTC, sy-records requested changes

2021-12-09 12:05 UTC, sy-records commented on aliyun-oss-wordpress.php
>  function oss_sanitize_file_name($filename)
参数应该是`$file`，数组类型。而不是filename

2021-12-12 09:03 UTC, 2551654928 commented on aliyun-oss-wordpress.php
>  function oss_sanitize_file_name($filename)
就是filename

2021-12-12 10:57 UTC, sy-records commented on aliyun-oss-wordpress.php
>  function oss_sanitize_file_name($filename)
see https://developer.wordpress.org/reference/hooks/wp_handle_upload_prefilter/

2023-07-25 00:27 UTC, closed without merging